### ISSUE TITLE
Invalid semantic version not accepted by SPM

### ISSUE THREAD

**Issue by KaiOelfke** [goodwhale/AspirinShot#2]
If you want feedback in another channel please let me know. I tried to use it the first time. My app is modularized with SPM meaning there's almost no code in the app target. I'd instead add a module to my app "ScreenshotsFeature", which depends on AspirinShot.

But now my Package.swift won't resolve due to:

> Invalid semantic version string '0.9'

In general SPM packages should use only semantic versioning as far as I know.

As a workaround I added branch: "main" as version. This also failed:

<img width="985" alt="Bildschirmfoto 2023-09-08 um 09 14 56" src="https://github.com/goodwhale/AspirinShot/assets/1190948/6916b010-79fd-4718-ac8f-fe3ba7317e14">

But that was maybe some Xcode issue. I had to resolve dependencies again.

**Comment by sowenjub** [comment]
Hey @KaiOelfke, here is perfect, but you can reach out on x or mastodon too.

I had no idea about that, thanks. I just pushed a 0.9.1 version.

I'm not sure about the SSL error though. I don't have that problem on my end. The files are hosted on Cloudflare R2.
Any chance proper semantic versioning fixed it?

**Comment by KaiOelfke** [comment]
No, this was Xcode for some reason failing to connect to Cloudflare or your server. I'd ignore that, if it doesn't happen again. I still have branch: "main" as workaround active. I'd have to change it to from: "0.9.1" in my Package.swift to use this fix.

**Comment by sowenjub** [comment]
Alright then. I'll close this for now.
Thanks a lot!
